# Generated by Django 4.0.6 on 2022-07-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_orderitems_total_amout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='quatity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
