# Generated by Django 4.0.6 on 2022-07-21 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_orderitems_quatity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitems',
            old_name='quatity',
            new_name='quantity',
        ),
    ]
