# Generated by Django 4.0.6 on 2022-07-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_quatity_orderitems_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
