# Generated by Django 4.0.6 on 2022-07-27 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_orderdetail_options_alter_orderitems_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippinginfo',
            name='orderItems',
        ),
    ]
