# Generated by Django 4.0.6 on 2022-07-29 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_shippinginfo_orderitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippinginfo',
            name='orderItems',
        ),
        migrations.AddField(
            model_name='orderitems',
            name='shippingInfo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.shippinginfo'),
        ),
    ]
